source 'https://rubygems.org'

gem 'puma'
gem 'sinatra'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'bcrypt'

group :development do
  gem 'sinatra-contrib'
  gem 'mysql2-client-general_log', github: 'abcang/mysql2-client-general_log', branch: 'rack_middleware'
end
